extends: 
  - concierge-auctions-react
plugins:
  - filenames
rules:
  filenames/match-exported: 2
  react/require-default-props: "off"
  jsx-a11y/img-has-alt: "off"
  no-underscore-dangle:
    - error
    - allowAfterThis: true
